package com.itcv.demo.sharding.dao;


import com.itcv.demo.sharding.po.SupplierPayrecords;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SupplierPayrecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_purchase_supplier_payrecords
     *
     * @mbggenerated Fri Aug 03 14:59:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_purchase_supplier_payrecords
     *
     * @mbggenerated Fri Aug 03 14:59:18 CST 2018
     */
    int insert(SupplierPayrecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_purchase_supplier_payrecords
     *
     * @mbggenerated Fri Aug 03 14:59:18 CST 2018
     */
    int insertSelective(SupplierPayrecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_purchase_supplier_payrecords
     *
     * @mbggenerated Fri Aug 03 14:59:18 CST 2018
     */
    SupplierPayrecords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_purchase_supplier_payrecords
     *
     * @mbggenerated Fri Aug 03 14:59:18 CST 2018
     */
    int updateByPrimaryKeySelective(SupplierPayrecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_purchase_supplier_payrecords
     *
     * @mbggenerated Fri Aug 03 14:59:18 CST 2018
     */
    int updateByPrimaryKey(SupplierPayrecords record);

    /**
     * 查询供应商余额
     * @param supplierPayrecords
     * @return
     */
    SupplierPayrecords  selectBalance(SupplierPayrecords supplierPayrecords);






}